using DevExpress.XtraBars;
using DevExpress.XtraEditors;
using studentManager_GUI.UI.classRoom;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace studentManager_GUI.UI
{
    public partial class classRoomUI : DevExpress.XtraEditors.XtraUserControl
    {
        public classRoomUI()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }
        void bbiPrintPreview_ItemClick(object sender, ItemClickEventArgs e)
        {
            gridControl.ShowRibbonPrintPreview();
        }

        addClassRoom addClassRoom = null;

        private void btnAddNew(object sender, ItemClickEventArgs e)
        {
            if(addClassRoom == null)
            {
                addClassRoom = new addClassRoom();
                addClassRoom.Show();
            }
        }
    }
}
