using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace studentManager_GUI.UI.studentsControl
{
    public partial class studentsUI_ : DevExpress.XtraEditors.XtraUserControl
    {
        public studentsUI_()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            studentManager_DTO.dbStudentManager dbContext = new studentManager_DTO.dbStudentManager();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.HOC_VIEN.Load();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = dbContext.HOC_VIEN.Local.ToBindingList();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        private void btnSAVE_Click(object sender, EventArgs e)
        {
        }
    }
}
